/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.cuaca;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.io.*;
import java.net.URL;
import javax.imageio.ImageIO;
import java.awt.Image;

public class WeatherAppFrame extends javax.swing.JFrame {
    // --- SERVICE & MODEL ---
    private final WeatherService service =
            new WeatherService(System.getProperty("f3a36af1108b9f270bdb8f22a0871515"));

    private final DefaultComboBoxModel<String> favoritModel = new DefaultComboBoxModel<>();
    private final DefaultTableModel tableModel = new DefaultTableModel(
            new Object[]{"Waktu","Kota","Suhu (°C)","Kondisi","Kelembaban (%)","Angin (m/s)","Deskripsi"}, 0);

    private final java.text.SimpleDateFormat df =
            new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    private final File FAVORIT_FILE = new File(System.getProperty("user.home"), ".cuaca_favorit.txt");


    /**
     * Creates new form WeatherAppFrame
     */
    public WeatherAppFrame() {
        initComponents();
        // setelah initComponents();
        myInit();
        setTitle("Aplikasi Cek Cuaca — Opsi A (OpenWeather Icon URL)"); // opsional
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKota = new javax.swing.JTextField();
        cmbFavorit = new javax.swing.JComboBox<>();
        btnCek = new javax.swing.JButton();
        btnTambahFavorit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        pDetail = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblKota = new javax.swing.JLabel();
        lblSuhu = new javax.swing.JLabel();
        lblKondisi = new javax.swing.JLabel();
        lblKelembaban = new javax.swing.JLabel();
        lblAngin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRiwayat = new javax.swing.JTable();
        btnMuatCSV = new javax.swing.JButton();
        btnSimpanCSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kota");

        jLabel2.setText("Favorit");

        txtKota.setText(" ");

        cmbFavorit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFavorit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFavoritItemStateChanged(evt);
            }
        });

        btnCek.setText("Cek Cuaca");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        btnTambahFavorit.setText("Tambah Favorit");
        btnTambahFavorit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahFavoritActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbFavorit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnCek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTambahFavorit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCek)
                    .addComponent(btnTambahFavorit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbFavorit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        lblIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Kota");

        jLabel4.setText("Suhu");

        jLabel5.setText("Kondisi");

        jLabel6.setText("Kelembaban");

        jLabel7.setText("Angin");

        lblKota.setText(" ");

        lblSuhu.setText(" ");

        lblKondisi.setText(" ");

        lblKelembaban.setText(" ");

        lblAngin.setText(" ");

        javax.swing.GroupLayout pDetailLayout = new javax.swing.GroupLayout(pDetail);
        pDetail.setLayout(pDetailLayout);
        pDetailLayout.setHorizontalGroup(
            pDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(57, 57, 57)
                .addGroup(pDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKelembaban, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKota, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAngin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pDetailLayout.setVerticalGroup(
            pDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblKota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblSuhu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblKondisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblKelembaban))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblAngin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(pDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tblRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRiwayat);

        btnMuatCSV.setText("Muat CSV");
        btnMuatCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuatCSVActionPerformed(evt);
            }
        });

        btnSimpanCSV.setText("Simpan CSV");
        btnSimpanCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnMuatCSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSimpanCSV)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMuatCSV)
                    .addComponent(btnSimpanCSV))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myInit() {
    // Hubungkan model ke komponen
    tblRiwayat.setModel(tableModel);
    cmbFavorit.setModel(favoritModel);

    favoritModel.addElement("— pilih favorit —");
    loadFavoritFromFile();

    // Placeholder awal UI
    if (lblKota != null) lblKota.setText("-");
    if (lblSuhu != null) lblSuhu.setText("-");
    if (lblKondisi != null) lblKondisi.setText("-");
    if (lblKelembaban != null) lblKelembaban.setText("-");
    if (lblAngin != null) lblAngin.setText("-");
    setIconByName("lainnya");
}

private void tampilkan(WeatherData d) {
    lblKota.setText(d.city);
    lblSuhu.setText(String.format("%.1f °C", d.temp));
    lblKondisi.setText(d.description);
    lblKelembaban.setText(d.humidity + " %");
    lblAngin.setText(String.format("%.1f m/s", d.wind));

    // Ambil ikon dari OpenWeather; fallback ke lokal jika gagal
    if (!setIconFromOpenWeather(d.iconCode)) {
        setIconByName(d.iconName);
    }

    tableModel.addRow(new Object[]{
        df.format(new java.utilDate(d.timestamp * 1000L)),
        d.city,
        String.format("%.1f", d.tempt),
        d.condition,
        d.humidity,
        String.format("%.1f", d.wind),
        d.description
    });
}

/** Kembalikan true jika berhasil load ikon dari URL OpenWeather */
private boolean setIconFromOpenWeather(String iconCode) {
    try {
        String url = "https://openweathermap.org/img/wn/" + iconCode + "@2x.png";
        Image img = ImageIO.read(new URL(url));
        if (img == null) throw new IOException("Gagal baca gambar.");
        Image scaled = img.getScaledInstance(128, 128, Image.SCALE_SMOOTH);
        lblIcon.setIcon(new ImageIcon(scaled));
        lblIcon.setText("");
        return true;
    } catch (Exception ex) {
        return false;
    }
}

/** Fallback: muat ikon lokal dari /icons/<name>.png (opsional) */
private void setIconByName(String name) {
    try {
        java.net.URL u = getClass().getResource("/icons/" + name + ".png");
        if (u != null) {
            Image img = ImageIO.read(u);
            if (img != null) {
                Image scaled = img.getScaledInstance(128, 128, Image.SCALE_SMOOTH);
                lblIcon.setIcon(new ImageIcon(scaled));
                lblIcon.setText("");
                return;
            }
        }
    } catch (Exception ignore) { /* fallback text */ }
    lblIcon.setIcon(null);
    lblIcon.setText(name.toUpperCase());
}

private void loadFavoritFromFile() {
    if (!FAVORIT_FILE.exists()) return;
    try (BufferedReader br = new BufferedReader(new FileReader(FAVORIT_FILE))) {
        String line;
        while ((line = br.readLine()) != null) {
            String city = line.trim();
            if (!city.isEmpty()) favoritModel.addElement(city);
        }
    } catch (IOException ignored) {}
}

private void persistFavoritToFile() {
    try (PrintWriter pw = new PrintWriter(new FileWriter(FAVORIT_FILE))) {
        for (int i = 1; i < favoritModel.getSize(); i++) { // lewati placeholder index 0
            pw.println(favoritModel.getElementAt(i));
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan favorit: " + e.getMessage());
    }
}

    
    
    private void btnTambahFavoritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahFavoritActionPerformed
        String city = txtKota.getText().trim();
        if (city.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kota kosong.");
            return;
        }
        for (int i = 0; i < favoritModel.getSize(); i++) {
            if (city.equalsIgnoreCase(favoritModel.getElementAt(i))) {
                JOptionPane.showMessageDialog(this, "Kota sudah ada di favorit.");
                return;
            }
        }
        favoritModel.addElement(city);
        persistFavoritToFile();
        JOptionPane.showMessageDialog(this, "Ditambahkan ke favorit.");
    }//GEN-LAST:event_btnTambahFavoritActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        String city = txtKota.getText().trim();
        if (city.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nama kota terlebih dahulu.");
            return;
        }
        btnCek.setEnabled(false);
        try {
            WeatherData d = service.fetch(city);
            tampilkan(d);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil cuaca: " + ex.getMessage());
        } finally {
            btnCek.setEnabled(true);
        }
    }//GEN-LAST:event_btnCekActionPerformed

    private void btnMuatCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuatCSVActionPerformed
        JFileChooser fc = new JFileChooser();
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                DefaultTableModel m = CsvUtil.loadCSV(fc.getSelectedFile());
                tblRiwayat.setModel(m);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Gagal muat: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnMuatCSVActionPerformed

    private void btnSimpanCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanCSVActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setSelectedFile(new File("riwayat-cuaca.csv"));
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                CsvUtil.saveTableToCSV(tblRiwayat, fc.getSelectedFile());
                JOptionPane.showMessageDialog(this, "Tersimpan.");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Gagal simpan: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSimpanCSVActionPerformed

    private void cmbFavoritItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFavoritItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int idx = cmbFavorit.getSelectedIndex();
            if (idx > 0) {
                String city = (String) cmbFavorit.getSelectedItem();
                txtKota.setText(city);
            }
        }
    }//GEN-LAST:event_cmbFavoritItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeatherAppFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnMuatCSV;
    private javax.swing.JButton btnSimpanCSV;
    private javax.swing.JButton btnTambahFavorit;
    private javax.swing.JComboBox<String> cmbFavorit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAngin;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblKelembaban;
    private javax.swing.JLabel lblKondisi;
    private javax.swing.JLabel lblKota;
    private javax.swing.JLabel lblSuhu;
    private javax.swing.JPanel pDetail;
    private javax.swing.JTable tblRiwayat;
    private javax.swing.JTextField txtKota;
    // End of variables declaration//GEN-END:variables
}
